/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StreetNetwork */

#ifndef _Included_StreetNetwork
#define _Included_StreetNetwork
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StreetNetwork
 * Method:    create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_StreetNetwork_create
  (JNIEnv *, jclass, jstring);

/*
 * Class:     StreetNetwork
 * Method:    toGeojsonPlain
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_StreetNetwork_toGeojsonPlain
  (JNIEnv *, jclass, jlong);

/*
 * Class:     StreetNetwork
 * Method:    toLanePolygonsGeojson
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_StreetNetwork_toLanePolygonsGeojson
  (JNIEnv *, jclass, jlong);

/*
 * Class:     StreetNetwork
 * Method:    toLaneMarkingsGeojson
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_StreetNetwork_toLaneMarkingsGeojson
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
