/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_osm2streets_StreetNetwork */

#ifndef _Included_org_osm2streets_StreetNetwork
#define _Included_org_osm2streets_StreetNetwork
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_osm2streets_StreetNetwork
 * Method:    create
 * Signature: (Ljava/lang/String;)Lorg/osm2streets/StreetNetwork;
 */
JNIEXPORT jobject JNICALL Java_org_osm2streets_StreetNetwork_create
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_osm2streets_StreetNetwork
 * Method:    toGeojsonPlain
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_osm2streets_StreetNetwork_toGeojsonPlain
  (JNIEnv *, jobject);

/*
 * Class:     org_osm2streets_StreetNetwork
 * Method:    toLanePolygonsGeojson
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_osm2streets_StreetNetwork_toLanePolygonsGeojson
  (JNIEnv *, jobject);

/*
 * Class:     org_osm2streets_StreetNetwork
 * Method:    toLaneMarkingsGeojson
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_osm2streets_StreetNetwork_toLaneMarkingsGeojson
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
