/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_osm2streets_StreetNetwork */

#ifndef _Included_org_osm2streets_StreetNetwork
#define _Included_org_osm2streets_StreetNetwork
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_osm2streets_StreetNetwork
 * Method:    create
 * Signature: ([B)Lorg/osm2streets/StreetNetwork;
 */
JNIEXPORT jobject JNICALL Java_org_osm2streets_StreetNetwork_create
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_osm2streets_StreetNetwork
 * Method:    getSurfaces
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_osm2streets_StreetNetwork_getSurfaces
  (JNIEnv *, jobject);

/*
 * Class:     org_osm2streets_StreetNetwork
 * Method:    getPaintAreas
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_osm2streets_StreetNetwork_getPaintAreas
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
